### ISSUE TITLE
Move sign up form higher up on page

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-energynewsnetwork#78]

**Comment by benlk** [comment]
Which signup form, on which pages?

**Comment by benlk** [comment]
The current order of things in the sidebar that appears at https://energynews.us/category/digest/ is as follows:

1. Saved Links
2. Mailchimp subscribe form, as a custom widget
3. Recent digests, in the form of one Link Roundups widget per region, for a total of 5.

The wireframe shows:

1. Signup form 
    <img width="253" alt="Screen Shot 2020-02-10 at 16 12 33" src="https://user-images.githubusercontent.com/1754187/74190308-2adccf80-4c20-11ea-95c6-d6b32e1bda48.png">

2. "Manage your subscription" as a Text Widget with centered button:
    <img width="250" alt="Screen Shot 2020-02-10 at 16 12 49" src="https://user-images.githubusercontent.com/1754187/74190351-37612800-4c20-11ea-87b7-38d96547c3b8.png">

3. the contact form from #79.

Reordering widgets on this page is possible, so long as this digest has its own sidebar.

In https://github.com/INN/umbrella-energynewsnetwork/issues/77#issuecomment-583161630 it was noted that the usual method for assigning a custom sidebar to an archive without coding wasn't working.

@MirandaEcho, which of these should we do?

- hardcode the sidebar to be displayed on this category page (~1h)
- try to fix it so that the sidebar displayed on the Digests template added in #83 matches the sidebar chosen in the Digests term metadata (unknown)
